services:
  fancontrol-agent:
    build:
      context: .
    container_name: fancontrol-agent
    restart: unless-stopped
    network_mode: host
    privileged: true
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - /sys:/sys:rw
      - /dev:/dev:rw
      - ./data-agent:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/syno/etc.defaults/scemd.xml:/usr/syno/etc.defaults/scemd.xml:rw
      - .:/repo
