version: '3.8'
services:
  fancontrol:
    build:
      context: .
      args:
        GIT_HASH: ${GIT_HASH:-unknown}
    container_name: fancontrol-web
    restart: unless-stopped
    network_mode: host
    volumes:
      - /sys:/sys:rw
      - /dev:/dev:rw
      - /volume1/docker/fancontrol-web/data:/app/data
    environment:
      - TZ=Europe/Moscow
      - FANCONTROL_CORS_ORIGINS=*
      - FANCONTROL_REPO=Biowolfx/fancontrol-web
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    privileged: true
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
