services:
  fancontrol-agent:
    image: fancontrol-web
    container_name: fancontrol-agent
    restart: unless-stopped
    network_mode: host
    privileged: true
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - /sys:/sys:rw
      - /dev:/dev:rw
      - ./data-agent:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/syno/etc.defaults/scemd.xml:/usr/syno/etc.defaults/scemd.xml:rw
      - /volume1/docker/fancontrol-web:/repo
    environment:
      - MODE=agent
      - SERVER_URL=ws://YOUR_SERVER_IP:5059
      - NODE_NAME=NAS Agent
      - CONTAINER_NAME=fancontrol-agent
